<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ClippedImageToPath</AssemblyName>
    <RootNamespace>ClippedImageToPath</RootNamespace>
    <Product>ClippedImageToPath</Product>
    <Version>1.4.0</Version>
    <FileVersion>1.4.0.0</FileVersion>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
    <InformationalVersion>1.4.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
    <PackageReference Include="FluentFTP" Version="52.1.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
